[[data]]
DOB = "Apr 18, 1990 (29)"
"Kit Number" = "1"
Name = "Wojciech Szczesny"
Nationality = "Poland"
Position = "Goalkeeper"

[[data]]
DOB = "Nov 10, 1992 (26)"
"Kit Number" = "37"
Name = "Mattia Perin"
Nationality = "Italy"
Position = "Goalkeeper"

[[data]]
DOB = "Jan 28, 1978 (41)"
"Kit Number" = "77"
Name = "Gianluigi Buffon"
Nationality = "Italy"
Position = "Goalkeeper"

[[data]]
DOB = "Mar 16, 1990 (29)"
"Kit Number" = "31"
Name = "Carlo Pinsoglio"
Nationality = "Italy"
Position = "Goalkeeper"

[[data]]
DOB = "Aug 12, 1999 (20)"
"Kit Number" = "4"
Name = "Matthijs de Ligt"
Nationality = "Netherlands"
Position = "Centre-Back"

[[data]]
DOB = "May 1, 1987 (32)"
"Kit Number" = "19"
Name = "Leonardo Bonucci"
Nationality = "Italy"
Position = "Centre-Back"

[[data]]
DOB = "Jul 29, 1994 (25)"
"Kit Number" = "24"
Name = "Daniele Rugani"
Nationality = "Italy"
Position = "Centre-Back"

[[data]]
DOB = "Mar 5, 1998 (21)"
"Kit Number" = "28"
Name = "Merih Demiral"
Nationality = "Turkey"
Position = "Centre-Back"

[[data]]
DOB = "Aug 14, 1984 (35)"
"Kit Number" = "3"
Name = "Giorgio Chiellini"
Nationality = "Italy"
Position = "Centre-Back"

[[data]]
DOB = "Jan 26, 1991 (28)"
"Kit Number" = "12"
Name = "Alex Sandro"
Nationality = "Brazil"
Position = "Left-Back"

[[data]]
DOB = "Jul 15, 1991 (28)"
"Kit Number" = "13"
Name = "Danilo"
Nationality = "Brazil"
Position = "Right-Back"

[[data]]
DOB = "Oct 20, 1992 (27)"
"Kit Number" = "2"
Name = "Mattia De Sciglio"
Nationality = "Italy"
Position = "Right-Back"

[[data]]
DOB = "Jan 12, 1994 (25)"
"Kit Number" = "23"
Name = "Emre Can"
Nationality = "Germany"
Position = "Defensive Midfield"

[[data]]
DOB = "Apr 2, 1990 (29)"
"Kit Number" = "5"
Name = "Miralem Pjanic"
Nationality = "Bosnia-Herzegovina"
Position = "Central Midfield"

[[data]]
DOB = "Dec 26, 1990 (28)"
"Kit Number" = "8"
Name = "Aaron Ramsey"
Nationality = "Wales"
Position = "Central Midfield"

[[data]]
DOB = "Apr 3, 1995 (24)"
"Kit Number" = "25"
Name = "Adrien Rabiot"
Nationality = "France"
Position = "Central Midfield"

[[data]]
DOB = "Jun 25, 1997 (22)"
"Kit Number" = "30"
Name = "Rodrigo Bentancur"
Nationality = "Uruguay"
Position = "Central Midfield"

[[data]]
DOB = "Apr 9, 1987 (32)"
"Kit Number" = "14"
Name = "Blaise Matuidi"
Nationality = "France"
Position = "Central Midfield"

[[data]]
DOB = "Apr 4, 1987 (32)"
"Kit Number" = "6"
Name = "Sami Khedira"
Nationality = "Germany"
Position = "Central Midfield"

[[data]]
DOB = "Feb 5, 1985 (34)"
"Kit Number" = "7"
Name = "Cristiano Ronaldo"
Nationality = "Portugal"
Position = "Left Winger"

[[data]]
DOB = "May 6, 1995 (24)"
"Kit Number" = "15"
Name = "Marko Pjaca"
Nationality = "Croatia"
Position = "Left Winger"

[[data]]
DOB = "Feb 16, 1994 (25)"
"Kit Number" = "33"
Name = "Federico Bernardeschi"
Nationality = "Italy"
Position = "Right Winger"

[[data]]
DOB = "Sep 14, 1990 (29)"
"Kit Number" = "11"
Name = "Douglas Costa"
Nationality = "Brazil"
Position = "Right Winger"

[[data]]
DOB = "May 26, 1988 (31)"
"Kit Number" = "16"
Name = "Juan Cuadrado"
Nationality = "Colombia"
Position = "Right Winger"

[[data]]
DOB = "Nov 15, 1993 (25)"
"Kit Number" = "10"
Name = "Paulo Dybala"
Nationality = "Argentina"
Position = "Second Striker"

[[data]]
DOB = "Dec 10, 1987 (31)"
"Kit Number" = "21"
Name = "Gonzalo Higuaín"
Nationality = "Argentina"
Position = "Centre-Forward"

[[data]]
DOB = "May 21, 1986 (33)"
"Kit Number" = "17"
Name = "Mario Mandzukic"
Nationality = "Croatia"
Position = "Centre-Forward"
